### ISSUE TITLE
Support custom format

### ISSUE THREAD

**Issue by nieaowei** [hikit-io/ctcu#2]
Placeholders:  `${title}`,  `${link}`
### Json
```json
{
    "title":"${title}",
    "url":"${link}"
}
```

### Toml
```toml
[[links]]
title = ${title}
link = ${link}
```
